### ISSUE TITLE
Error management

### ISSUE THREAD

**Issue by acondura** [faraweilyas/sshbunny#1]
Hello Ilyas,

First, I want to thank for a great, simple way to use SSH connections through PHP. It's exactly what I was looking for.

I'm building a UI tool to manage web servers and their websites that are built with https://docksal.io. I've gotten as far as adding servers but when adding a server that doesn't use Docksal meaning, it can't SSH connect to the server using the 'docksal' user, it simply throws this error on a blank page:

> Could not authenticate, rejected by server using: 'docksal'

I tried the following

          try {
            $sshOutput = (new SSHBunny('remote', 'KEY', $IP, 22, "docksal"))
              ->setKeys($pubKey, $privKey)
              ->initialize()
              ->exec("fin pl -a")
              ->getData();
            ksm([$sIP, $sshOutput], $sIP.' - sshOutput');
          } catch (Exception $e) {
            ksm($e, 'error');
          }

but still the same error.

I started reading through https://github.com/faraweilyas/sshbunny/blob/master/src/SSHBunny.php and that's how I came up with the code above.

Do you think you could please let me know what I could use?

**Comment by faraweilyas** [comment]
i'm just seeing this now...

make sure you give your public and private keys the right permissions `sudo chmod 400 public_key`

lmk if that solves your issue!

**Comment by acondura** [comment]
Sorry for the delay. That fixed it.
